
result = 0
#input = "FFFR 4"
#input = "F 6-R 1-F 4-RFF 2-LFF 1-LFFFR 1-F 2-R 1-F 5"
#input = "L 1-FR 1-FFFFFL 1-FFFFL 1-F 12-L 1-F 12-L 1-F 12-L 1-FFFFL 1-FFFFFFFFR 1-FFFR 1-FFFL 1"
#input = "FFRFLFLFFRFRFLFF 3-R 1-FFLFRFRFLFFF 3-R 1-FFFFFF 3-L 1-FFFRFLFLFRFF 2-R 1-FFFRFLFLFRFF 3-R 1-FFFFFF 1-L 1-FFRFLFLFFRFRFLFF 3-R 1-FFLFRFRFFLFLFRFF 2-L 1-FFLFRFRFFLFLFRFF 3-R 1-FFRFLFLFFRFRFLFF 2-R 1-FFRFLFLFFRFRFLFF 2-L 1-FFFFFF 3-R 1-FFFRFLFLFRFF 5-R 1-FFLFRFRFLFFF 1-L 1-FFLFRFRFFLFLFRFF 2-R 1-FFRFLFLFFRFRFLFF 2-L 1"
#input = "FFLFRFRFFLFLFRFF 5-L 1-FFFRFLFLFRFF 4-L 1-FFLFRFRFFLFLFRFF 8-L 1-FFLFRFRFFLFLFRFF 4-L 1-FFFFFF 3-R 1"

parts = input.split('-')

parts.each do |str|
	str =~ /([FLR]+)\s(\d+)/
	tmp = 0
	count = $2.to_i
	$1.to_s.split(//).each {|c| tmp+=1 if c == 'F'}
	tmp *= count
	result += tmp
end

puts result




